version: '2.3'
services:
  todo-front:
    image: todo-front:latest
  todo-mongo:
    image: todo-mongo:latest
    restart: always
    healthcheck:
      test: ["CMD", "/usr/local/bin/mongo-healthcheck"]
      interval: 5s
      timeout: 1s
      retries: 5
  todo-api:
    image: todo-api:latest
    restart: always
    environment:
      - MONGO_HOST=todo-mongo
      - MONGO_PORT=27017
      - MONGO_DB=tasksDB
    depends_on:
      todo-mongo:
        condition: service_healthy
  todo-gateway:
    image: todo-gateway:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      todo-mongo:
        condition: service_healthy
      todo-api:
        condition: service_started
