apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: todo-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources: {}
        livenessProbe:
          httpGet:
            path: /api/health/task
            port: 3000
        readinessProbe:
          httpGet:
            path: /api/health/task
            port: 3000
        env:
          - name: MONGO_HOST
            value: "todo-mongo"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DB
            value: "tasksDB"
status: {}
