apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-auth-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-auth-deployment
  labels:
    app: todo-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-auth
  template:
    metadata:
      labels:
        app: todo-auth
    spec:
      containers:
      - name: todo-auth
        image: todo-auth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits: 
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /auth/health
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /auth/health
            port: 3000
          initialDelaySeconds: 50
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_PORT
          - name: MONGO_DB
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_DB
          - name: SUPER_SECRET
            valueFrom:
              secretKeyRef:
                name: jwtconfig
                key: SUPER_SECRET
          - name: TOKEN_EXPIRATION
            valueFrom:
              secretKeyRef:
                name: jwtconfig
                key: TOKEN_EXPIRATION
